---

name: "Build and Deploy"

on:
  workflow_dispatch:
  push:
    branches:
      - "GAIA-17439-migrate-api-client-ci-cd-workflows-from-circle-ci-to-git-hub-actions"

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

permissions:
  contents: "read"
  pages: "write"

jobs:
  build:
    runs-on: "ubuntu-20.04"
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v3"

      # Required for sphinx-multiversion
      - run: "git fetch --depth=1 origin '+refs/tags/*:refs/remotes/origin/*'"

      - name: "Setup Python"
        uses: "actions/setup-python@v4"
        with:
          python-version: "3.6.15"

      - name: "Install dependencies"
        run: |
          pip install poetry==1.2.0a2 poetry-dynamic-versioning==0.17.1
          poetry install --with docs

      - name: "Build package"
        run: "poetry build"

      - name: "Build docs"
        run: "poetry run sphinx-multiversion docs docs/_build/html"

      - name: "Upload artifact"
        uses: "actions/upload-pages-artifact@v1"
        with:
          path: "docs/_build/html"

  deploy:
    runs-on: "ubuntu-latest"
    environment:
      name: "github-pages"
      url: "${{ steps.deployment.outputs.page_url }}"
    needs: "build"
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v3"

      # TODO: Logic to push to PyPI
      # - name: "Deploy to PyPI"
      #   run: "poetry publish"

      # - name: Deploy to GitHub Pages
      #   id: "deployment"
      #   uses: "actions/deploy-pages@v1"
