---

# testing with a forked version
name: "Build and Deploy"

on:
  workflow_dispatch:
  push:
    branches:
      - "test-main"
    tags:
      - "v1.**"


concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

permissions:
  contents: "read"
  id-token: "write"
  pages: "write"

jobs:
  build:
    runs-on: "ubuntu-20.04"
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v3"
        with:
          ref: "test-main"

      # Required for sphinx-multiversion
      - run: "git fetch --depth=1 origin '+refs/tags/*:refs/remotes/origin/*'"

      - name: "Setup Python"
        uses: "actions/setup-python@v4"
        with:
          python-version: "3.6.15"

      - name: "Install dependencies"
        run: |
          pip install poetry==1.2.0a2 poetry-dynamic-versioning==0.17.1
          poetry install --with docs

      - name: "Build package"
        run: "poetry build"

      - name: "Build docs"
        run: "poetry run sphinx-multiversion docs docs/_build/html"

      - run: |
          # With sphinxcontrib-versioning, we would generate a separate directory of docs
          # for each version tag and branch, but also have the default branch's i.e. `main`
          # docs at the top level.`sphinx-multiversion` only generates the separate
          # directories. To avoid breaking links, we copy the the root ref docs (i.e.,
          # the `main` branch docs) to the parent directory containing all docs.
          cp -R "docs/_build/html/test-main/." docs/_build/html

      - name: "Upload artifact"
        uses: "actions/upload-pages-artifact@v1"
        with:
          path: "docs/_build/html"

  deploy:
    runs-on: "ubuntu-latest"
    environment:
      name: "github-pages"
      url: "${{ steps.deployment.outputs.page_url }}"
    needs: "build"
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v3"

      - name: "Deploy to PyPI"
        if: "${{ github.ref_type == 'branch' }}"
        run: echo "Found ${{ github.ref_name }}"

      - name: "Deploy to PyPI"
        if: "${{ github.ref_type == 'tag' }}"
        run: echo "Found ${{ github.ref_name }}"

      - name: Deploy to GitHub Pages
        id: "deployment"
        uses: "actions/deploy-pages@v1"
